db:
  username: ${username.value:postgres}
  password: pass
  driver: PostgresDriver
  url: postgres:5432
  hosts: localhost,127.0.0.1
  pool:
    size: 10
    timeout: 12
  pools:
    - size: 1
      timeout: 1
    - size: 2
      timeout: 2
    - size: 3
      timeout: 3
  properties:
    first: 123
    second: 546
    third.value: third
spring.profiles.active: qa


logging:
  level:
    root: WARN
    org.andreev.spring.datsbase.pool.ConnectionPool: INFO
  file:
    path: /
    name: fileYmlConfig.log
